### ISSUE TITLE
Is backend.json missing from minion-vm?

### ISSUE THREAD

**Issue by jzy2000** [mozilla/minion-vm#12]
Is backend.json missing from minion-vm?

me@me:~/minion-vm-master$ sudo docker build -t 'mozilla/minion-backend'  -f Dockerfile-backend  .
Sending build context to Docker daemon 49.66 kB
Step 1 : FROM ubuntu:14.04
 ---> 3876b81b5a81
Step 2 : MAINTAINER April King april@mozilla.com
 ---> Using cache
 ---> 97aebe63fb68
Step 3 : ENV MINION_BACKEND /opt/minion/minion-backend
 ---> Using cache
 ---> 8dbeab6518a1
Step 4 : ENV MINION_DOCKERIZED true
 ---> Using cache
 ---> 9857548ff15a
Step 5 : EXPOSE 8383
 ---> Using cache
 ---> 0315b72daa3f
**Step 6 : COPY backend.json /tmp/backend.json
lstat backend.json: no such file or directory**

**Comment by april** [comment]
Hmm, that should have been removed from the Dockerfile, let me go ahead and fix it.

**Comment by april** [comment]
Okay, should be fixed in #13.  The docker images just use the minion default backend.json file, so there's no need to copy it in there anymore.

**Comment by jzy2000** [comment]
I don't know if anyone ever tested Docker installation on Ubuntu12.04, I got lots of errors just for backend. Error snippets below:
BTW, Vagrant also failed for errors.

me@me:~/minion-vm-master$ sudo docker build -t 'mozilla/minion-backend'  -f Dockerfile-backend  .
......

Setting up libldap-2.4-2 (2.4.28-1.1ubuntu4.6) ...
Setting up libpcap0.8 (1.1.1-10) ...
Setting up librtmp0 (2.4~20110711.gitc28f1bab-1) ...
Setting up openssl (1.0.1-4ubuntu5.33) ...
Setting up ca-certificates (20141019ubuntu0.12.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
Updating certificates in /etc/ssl/certs... 173 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
Setting up libcurl3 (7.22.0-3ubuntu4.15) ...
Setting up libexpat1 (2.0.1-7.2ubuntu1.2) ...
Setting up libgmp10 (2:5.0.2+dfsg-2ubuntu1) ...
Setting up libgnutls-openssl27 (2.12.14-5ubuntu3.11) ...
…
…
Setting up mongodb-clients (1:2.0.4-1ubuntu2.1) ...
Setting up mongodb-server (1:2.0.4-1ubuntu2.1) ...
Adding system user `mongodb' (UID 101) ...
Adding new user`mongodb' (UID 101) with group `nogroup' ...
Not creating home directory`/home/mongodb'.
Adding group `mongodb' (GID 103) ...
Done.
Adding user`mongodb' to group `mongodb' ...
Adding user mongodb to group mongodb
Done.
invoke-rc.d: policy-rc.d denied execution of start.
Setting up ssl-cert (1.0.28ubuntu0.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
Setting up postfix (2.9.6-1~12.04.3) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
Adding group`postfix' (GID 105) ...
Done.
Adding system user `postfix' (UID 102) ...
Adding new user`postfix' (UID 102) with group `postfix' ...
Not creating home directory`/var/spool/postfix'.
Creating /etc/postfix/dynamicmaps.cf
Adding tcp map entry to /etc/postfix/dynamicmaps.cf
Adding sqlite map entry to /etc/postfix/dynamicmaps.cf
Adding group `postdrop' (GID 106) ...
Done.
setting myhostname: f1f0f24b9f1a
setting alias maps
setting alias database
mailname is not a fully qualified domain name.  Not changing /etc/mailname.
setting destinations: /etc/mailname, f1f0f24b9f1a, localhost.localdomain, localhost
setting relayhost: 
setting mynetworks: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
setting mailbox_size_limit: 0
setting recipient_delimiter: +
setting inet_interfaces: all
setting inet_protocols: all
/etc/aliases does not exist, creating it.
WARNING: /etc/aliases exists, but does not have a root alias.

Postfix is now set up with a default configuration.  If you need to make

changes, edit
/etc/postfix/main.cf (and others) as needed.  To view Postfix configuration
values, see postconf(1).

After modifying main.cf, be sure to run '/etc/init.d/postfix reload'.

Running newaliases
invoke-rc.d: policy-rc.d denied execution of restart.
Setting up tcpd (7.6.q-21) ...
Setting up libffi-dev (3.0.11~rc1-5) ...
Setting up nmap (5.21-1.1ubuntu1) ...
Setting up rabbitmq-server (2.7.1-0ubuntu4) ...
Adding group `rabbitmq' (GID 107) ...
Done.
Adding system user`rabbitmq' (UID 103) ...
Adding new user `rabbitmq' (UID 103) with group`rabbitmq' ...
Not creating home directory `/var/lib/rabbitmq'.
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libswitch-perl (2.16-2) ...
Setting up perl-modules (5.14.2-6ubuntu2.4) ...
Setting up perl (5.14.2-6ubuntu2.4) ...
update-alternatives: using /usr/bin/prename to provide /usr/bin/rename (rename) in auto mode.
Setting up stunnel4 (3:4.42-1ubuntu0.1) ...
Warning: The home dir /var/run/stunnel4 you specified can't be accessed: No such file or directory
Adding system user`stunnel4' (UID 104) ...
Adding new group `stunnel4' (GID 108) ...
Adding new user`stunnel4' (UID 104) with group `stunnel4' ...
Not creating home directory`/var/run/stunnel4'.
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
Reading package lists...
Building dependency tree...
Reading state information...
rabbitmq-server is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
/tmp/backend.sh: line 24: minion-env/bin/activate: No such file or directory
/tmp/backend.sh: line 30: cd: minion-backend: No such file or directory
python: can't open file 'setup.py': [Errno 2] No such file or directory
/tmp/backend.sh: line 40: git: command not found
/tmp/backend.sh: line 41: cd: /opt/minion/minion-nmap-plugin: No such file or directory
python: can't open file 'setup.py': [Errno 2] No such file or directory
cp: cannot stat `/opt/minion/minion-backend/scripts/minion-init': No such file or directory
chown: cannot access`/etc/init.d/minion': No such file or directory
chmod: cannot access `/etc/init.d/minion': No such file or directory
update-rc.d: /etc/init.d/minion: file does not exist
Starting rabbitmq-server: SUCCESS
rabbitmq-server.
minion: unrecognized service
/tmp/backend.sh: line 68: minion-db-init: command not found
minion: unrecognized service
Stopping rabbitmq-server: rabbitmq-server.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
The command '/bin/sh -c /bin/bash -c /tmp/backend.sh' returned a non-zero code: 1

Date: Fri, 5 Feb 2016 15:19:14 -0800
