### ISSUE TITLE
No updates

### ISSUE THREAD

**Issue by bibkam** [mozilla/minion-vm#18]
Hello,
The Mozilla Minion is still maintained ? there is no update from 2 years ago ! 
Are you planning a new release in the next days ?
Best Regards
BIBKAM

**Comment by psiinon** [comment]
No, I'm afraid Minion is no longer being maintained

**Comment by bibkam** [comment]
Thank you so much Simon for your quick reply.
Another question please, have you any suggestion about similar solutions ?
