### ISSUE TITLE
Use docker-compose

### ISSUE THREAD

**Issue by andymckay** [mozilla/minion-vm#2]
Docker compose provides a nice way to tie together containers and would relieve the need to have .sh scripts for that.

**Comment by april** [comment]
Sure!  The primary reason why I used a shell script is because I could reuse the code between Docker and Vagrant.  If we can use docker-compose while still sticking to a nice vagrant up, then I'm all for it.

**Comment by andymckay** [comment]
Ah that's a good point, in the past I've stuck to one or the other trying to do both seems like hard work :)

**Comment by april** [comment]
It's a bit complicated, yes.  :)

**Comment by afeld** [comment]
@marumari Would you be open to going Docker-only? I'm trying the installation as a newcomer, and having to re-install everything for every build is pretty painful(ly slow). I've already made some progress to splitting it up to take advantage of Docker's caching, if you'd be interested in a PR.

**Comment by april** [comment]
Being Docker-only for deployments is fine, but Docker-only is really lousy for development, especially if you're on OS X or Windows.  If you can make it as painless on Windows and OS X with Docker as it currently is with Vagrant, including shared source directories, I'm certainly up to the idea of going only to Docker.

**Comment by Creased** [comment]
I've opened a PR #17 to provide the ability to use Vagrant along with Docker Compose.
